In [6]:
import numpy as np

a=[2,6,5,3,4,7,9,3,2]
x=np.reshape(a,(3,3))

np.linalg.inv(x)

array([[-0.0718232 ,  0.01657459,  0.12154696],
       [ 0.31491713, -0.22651934,  0.00552486],
       [-0.14917127,  0.26519337, -0.05524862]])

In [13]:
import numpy as np

a=[5,4,6,3]
x=np.reshape(a,(2,2))
print (x)
print(np.linalg.eig(x))
print (np.linalg.eigvals(x))

[[5 4]
 [6 3]]
(array([ 9., -1.]), array([[ 0.70710678, -0.5547002 ],
       [ 0.70710678,  0.83205029]]))
[ 9. -1.]


In [14]:
from scipy.sparse import coo_matrix, hstack
A = coo_matrix([[1, 2], [3, 4]])
B = coo_matrix([[5], [6]])
hstack([A,B]).toarray()


array([[1, 2, 5],
       [3, 4, 6]], dtype=int64)

In [15]:
from scipy.sparse import coo_matrix, hstack
A = coo_matrix([[1, 2], [3, 4]])
B = coo_matrix([[5], [6]])
hstack([A,B]).toarray()

array([[1, 2, 5],
       [3, 4, 6]], dtype=int64)